// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';

// Auth Login Check

export const USER_LOGIN_CHECK_REQUEST = 'USER_LOGIN_CHECK_REQUEST';
export const USER_LOGIN_CHECK_SUCCESS = 'USER_LOGIN_CHECK_SUCCESS';
export const USER_LOGIN_CHECK_FAILURE = 'USER_LOGIN_CHECK_FAILURE';

//Sticky
export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE = 'NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS = 'FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS = 'UPDATE_ALL_NOTES_SUCCESS';


// User balance

export const USER_BALANCE_REQUEST = 'USER_BALANCE_REQUEST';
export const USER_BALANCE_SUCCESS = 'USER_BALANCE_SUCCESS';
export const USER_BALANCE_FAILURE = 'USER_BALANCE_FAILURE';
// change Password

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

// Match List
export const MATCH_LIST_REQUEST = 'MATCH_LIST_REQUEST';
export const MATCH_LIST_SUCCESS = 'MATCH_LIST_SUCCESS';
export const MATCH_LIST_FAILURE = 'MATCH_LIST_FAILURE';


// cOMPLETE SPORT LIST
export const COMPLETE_SPORT_LIST_REQUEST = 'COMPLETE_SPORT_LIST_REQUEST';
export const COMPLETE_SPORT_LIST_SUCCESS = 'COMPLETE_SPORT_LIST_SUCCESS';
export const COMPLETE_SPORT_LIST_FAILURE = 'COMPLETE_SPORT_LIST_FAILURE';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';

//USER_LENA_DENA
export const USER_LENA_DENA_REQUEST = 'USER_LENA_DENA_REQUEST';
export const USER_LENA_DENA_SUCCESS = 'USER_LENA_DENA_SUCCESS';
export const USER_LENA_DENA_FAILURE = 'USER_LENA_DENA_FAILURE';

//.....................
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

//........................
export const COIN_UPDATE_REQUEST = 'COIN_UPDATE_REQUEST';
export const COIN_UPDATE_SUCCESS = 'COIN_UPDATE_SUCCESS';
export const COIN_UPDATE_FAILURE = 'COIN_UPDATE_FAILURE';

//.............INPLAY ODD POSDITION 
export const INPLAY_ODD_POSITION_REQUEST = 'INPLAY_ODD_POSITION_REQUEST';
export const INPLAY_ODD_POSITION_SUCCESS = 'INPLAY_ODD_POSITION_SUCCESS';
export const INPLAY_ODD_POSITION_FAILURE = 'INPLAY_ODD_POSITION_FAILURE';
//........................CASINO BET LIST
export const CASINO_DIAMOND_BET_LIST_REQUEST = 'CASINO_DIAMOND_BET_LIST_REQUEST';
export const CASINO_DIAMOND_BET_LIST_SUCCESS = 'CASINO_DIAMOND_BET_LIST_SUCCESS';
export const CASINO_DIAMOND_BET_LIST_FAILURE = 'CASINO_DIAMOND_BET_LIST_FAILURE';

//........create Account 
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';


//...............USER PROFIT LOSS
export const USER_PROFITLOSS_REQUEST = 'USER_PROFITLOSS_REQUEST';
export const USER_PROFITLOSS_SUCCESS = 'USER_PROFITLOSS_SUCCESS';
export const USER_PROFITLOSS_FAILURE = 'USER_PROFITLOSS_FAILURE';
//................usER lEDEGER LIST
export const USER_LEDGER_LIST_REQUEST = 'USER_LEDGER_LIST_REQUEST';
export const USER_LEDGER_LIST_SUCCESS = 'USER_LEDGER_LIST_SUCCESS';
export const USER_LEDGER_LIST_FAILURE = 'USER_LEDGER_LIST_FAILURE';

//................User LEDEGER LIST
export const USER_LEDGER_CREDIT_DEBIT_REQUEST = 'USER_LEDGER_CREDIT_DEBIT_REQUEST';
export const USER_LEDGER_CREDIT_DEBIT_SUCCESS = 'USER_LEDGER_CREDIT_DEBIT_SUCCESS';
export const USER_LEDGER_CREDIT_DEBIT_FAILURE = 'USER_LEDGER_CREDIT_DEBIT_FAILURE';


//...............PlusMinusByMarketIdByUserWise

export const PlusMinusByMarketIdByUserWise_LIST_REQUEST = 'PlusMinusByMarketIdByUserWise_LIST_REQUEST';
export const PlusMinusByMarketIdByUserWise_LIST_SUCCESS = 'PlusMinusByMarketIdByUserWise_LIST_SUCCESS';
export const PlusMinusByMarketIdByUserWise_LIST_FAILURE = 'PlusMinusByMarketIdByUserWise_LIST_FAILURE';

//getPlusMinusByMarketId

export const GET_PLUS_MINUS_BY_MARKET_ID_REQUEST = 'GET_PLUS_MINUS_BY_MARKET_ID_REQUEST';
export const GET_PLUS_MINUS_BY_MARKET_ID_SUCCESS = 'GET_PLUS_MINUS_BY_MARKET_ID_SUCCESS';
export const GET_PLUS_MINUS_BY_MARKET_ID_FAILURE = 'GET_PLUS_MINUS_BY_MARKET_ID_FAILURE';

//............................

export const MATCH_DETAIL_REQUEST = 'MATCH_DETAIL_REQUEST';
export const MATCH_DETAIL_SUCCESS = 'MATCH_DETAIL_SUCCESS';
export const MATCH_DETAIL_FAILURE = 'MATCH_DETAIL_FAILURE';
export const USER_LEDGER_CLEAR = 'USER_LEDGER_CLEAR';


// FETCH_DIAMOND_CASINO_REPORT
export const FETCH_DIAMOND_CASINO_REPORT_REQUEST = 'FETCH_DIAMOND_CASINO_REPORT_REQUEST';
export const FETCH_DIAMOND_CASINO_REPORT_SUCCESS = 'FETCH_DIAMOND_CASINO_REPORT_SUCCESS';
export const FETCH_DIAMOND_CASINO_REPORT_FAILURE = 'FETCH_DIAMOND_CASINO_REPORT_FAILURE';

//shareDetails
export const FETCH_SHARE_DETAILS_REQUEST = 'FETCH_SHARE_DETAILS_REQUEST';
export const FETCH_SHARE_DETAILS_SUCCESS = 'FETCH_SHARE_DETAILS_SUCCESS';
export const FETCH_SHARE_DETAILS_FAILURE = 'FETCH_SHARE_DETAILS_FAILURE';

// userStatement

export const USER_STATEMENT_REQUEST = 'USER_STATEMENT_REQUEST';
export const USER_STATEMENT_SUCCESS = 'USER_STATEMENT_SUCCESS';
export const USER_STATEMENT_FAILURE = 'USER_STATEMENT_FAILURE';

// userActivity

export const USER_ACTIVITY_REQUEST = 'USER_ACTIVITY_REQUEST';
export const USER_ACTIVITY_SUCCESS = 'USER_ACTIVITY_SUCCESS';
export const USER_ACTIVITY_FAILURE = 'USER_ACTIVITY_FAILURE';

// userLoginActivity

export const USER_LOGIN_ACTIVITY_REQUEST = 'USER_LOGIN_ACTIVITY_REQUEST';
export const USER_LOGIN_ACTIVITY_SUCCESS = 'USER_LOGIN_ACTIVITY_SUCCESS';
export const USER_LOGIN_ACTIVITY_FAILURE = 'USER_LOGIN_ACTIVITY_FAILURE';

//sportsBetsList

export const SPORTS_BET_LIST_REQUEST = 'SPORTS_BET_LIST_REQUEST';
export const SPORTS_BET_LIST_SUCCESS = 'SPORTS_BET_LIST_SUCCESS';
export const SPORTS_BET_LIST_FAILURE = 'SPORTS_BET_LIST_FAILURE';

// clientListByMarketId

export const CLIENT_LIST_BY_MARKET_ID_REQUEST = 'CLIENT_LIST_BY_MARKET_ID_REQUEST';
export const CLIENT_LIST_BY_MARKET_ID_SUCCESS = 'CLIENT_LIST_BY_MARKET_ID_SUCCESS';
export const CLIENT_LIST_BY_MARKET_ID_FAILURE = 'CLIENT_LIST_BY_MARKET_ID_FAILURE';

//userCommissionReport

export const USER_COMMISSION_REPORT_REQUEST = 'USER_COMMISSION_REPORT_REQUEST';
export const USER_COMMISSION_REPORT_SUCCESS = 'USER_COMMISSION_REPORT_SUCCESS';
export const USER_COMMISSION_REPORT_FAILURE = 'USER_COMMISSION_REPORT_FAILURE';

// User Search Api 

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_FAILURE = 'USER_SEARCH_FAILURE';
export const USER_SEARCH_CLIEAR = 'USER_SEARCH_CLIEAR';



// userDetails
export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_FAILURE = 'USER_DETAIL_FAILURE';
export const USER_DETAIL_CLEAR = 'USER_DETAIL_CLEAR';

// casino Round Wise Data 

export const CASINO_ROUND_WISE_REQUEST = 'CASINO_ROUND_WISE_REQUEST';
export const CASINO_ROUND_WISE_SUCCESS = 'CASINO_ROUND_WISE_SUCCESS';
export const CASINO_ROUND_WISE_FAILURE = 'CASINO_ROUND_WISE_FAILURE';

// dayWiseCasinoReport

export const CASINO_DAY_WISE_REQUEST = 'CASINO_DAY_WISE_REQUEST';
export const CASINO_DAY_WISE_SUCCESS = 'CASINO_DAY_WISE_SUCCESS';
export const CASINO_DAY_WISE_FAILURE = 'CASINO_DAY_WISE_FAILURE';

//.......Domain Setting By Domian NAme

export const DOMIAN_SETTING_BY_DOMAIN_NAME_REQUEST = 'DOMIAN_SETTING_BY_DOMAIN_NAME_REQUEST';
export const DOMIAN_SETTING_BY_DOMAIN_NAME_SUCCESS = 'DOMIAN_SETTING_BY_DOMAIN_NAME_SUCCESS';
export const DOMIAN_SETTING_BY_DOMAIN_NAME_FAILURE = 'DOMIAN_SETTING_BY_DOMAIN_NAME_FAILURE';

// ............secure code


export const SECURE_CODE_REQUEST = 'SECURE_CODE_REQUEST';
export const SECURE_CODE_SUCCESS = 'SECURE_CODE_SUCCESS';
export const SECURE_CODE_FAILURE = 'SECURE_CODE_FAILURE';


// completedFancyByMarketId

export const COMPLATED_FANCY_BY_MARKET_ID_REQUEST = 'COMPLATED_FANCY_BY_MARKET_ID_REQUEST';
export const COMPLATED_FANCY_BY_MARKET_ID_SUCCESS = 'COMPLATED_FANCY_BY_MARKET_ID_SUCCESS';
export const COMPLATED_FANCY_BY_MARKET_ID_FAILURE = 'COMPLATED_FANCY_BY_MARKET_ID_FAILURE';

// getSessionPositionBySelectionId

export const SESSION_POSITION_BY_SELECTION_ID_REQUEST = 'SESSION_POSITION_BY_SELECTION_ID_REQUEST';
export const SESSION_POSITION_BY_SELECTION_ID_SUCCESS = 'SESSION_POSITION_BY_SELECTION_ID_SUCCESS';
export const SESSION_POSITION_BY_SELECTION_ID_FAILURE = 'SESSION_POSITION_BY_SELECTION_ID_FAILURE';

//getOddsPosition
export const ODDS_POSSITION_REQUEST = 'ODDS_POSSITION_REQUEST';
export const ODDS_POSSITION_SUCCESS = 'ODDS_POSSITION_SUCCESS';
export const ODDS_POSSITION_FAILURE = 'ODDS_POSSITION_FAILURE';

// Decision Reset Comm Api

export const DECISION_RESET_COMM_REQUEST = 'DECISION_RESET_COMM_REQUEST';
export const DECISION_RESET_COMM_SUCCESS = 'DECISION_RESET_COMM_SUCCESS';
export const DECISION_RESET_COMM_FAILURE = 'DECISION_RESET_COMM_FAILURE';

// Decision Reset Commition

export const DECISION_RESET_COMM_LIST_REQUEST = 'DECISION_RESET_COMM_LIST_REQUEST';
export const DECISION_RESET_COMM_LIST_SUCCESS = 'DECISION_RESET_COMM_LIST_SUCCESS';
export const DECISION_RESET_COMM_LIST_FAILURE = 'DECISION_RESET_COMM_LIST_FAILURE';

// get plusminuscasino details

export const GET_PLUS_MINUS_CASINO_DETAIL_REQUEST = 'GET_PLUS_MINUS_CASINO_DETAIL_REQUEST';
export const GET_PLUS_MINUS_CASINO_DETAIL_SUCCESS = 'GET_PLUS_MINUS_CASINO_DETAIL_SUCCESS';
export const GET_PLUS_MINUS_CASINO_DETAIL_FAILURE = 'GET_PLUS_MINUS_CASINO_DETAIL_FAILURE';

//casino getProfitLossPos

export const CASINO_PROFIT_LOSS_REQUEST = 'CASINO_PROFIT_LOSS_REQUEST';
export const CASINO_PROFIT_LOSS_SUCCESS = 'CASINO_PROFIT_LOSS_SUCCESS';
export const CASINO_PROFIT_LOSS_FAILURE = 'CASINO_PROFIT_LOSS_FAILURE';

// casino realTimeDataPosDataDiamondCasino

export const CASINO_REAL_TIME_DIAMOND_CASINO_REQUEST = 'CASINO_REAL_TIME_DIAMOND_CASINO_REQUEST';
export const CASINO_REAL_TIME_DIAMOND_CASINO_SUCCESS = 'CASINO_REAL_TIME_DIAMOND_CASINO_SUCCESS';
export const CASINO_REAL_TIME_DIAMOND_CASINO_FAILURE = 'CASINO_REAL_TIME_DIAMOND_CASINO_FAILURE';

// Casino resport By user
export const CASINO_REPORT_BY_USER_REQUEST = 'CASINO_REPORT_BY_USER_REQUEST';
export const CASINO_REPORT_BY_USER_SUCCESS = 'CASINO_REPORT_BY_USER_SUCCESS';
export const CASINO_REPORT_BY_USER_FAILURE = 'CASINO_REPORT_BY_USER_FAILURE';

// getDiamondCasinoByEventId
export const GET_DIAMOND_CASINO_BY_EVENT_ID_REQUEST = 'GET_DIAMOND_CASINO_BY_EVENT_ID_REQUEST';
export const GET_DIAMOND_CASINO_BY_EVENT_ID_SUCCESS = 'GET_DIAMOND_CASINO_BY_EVENT_ID_SUCCESS';
export const GET_DIAMOND_CASINO_BY_EVENT_ID_FAILURE = 'GET_DIAMOND_CASINO_BY_EVENT_ID_FAILURE';

//  userPositionByMarketId By Maekt Id 

export const USER_POSITION_BY_MARKETID_REQUEST = 'USER_POSITION_BY_MARKETID_REQUEST';
export const USER_POSITION_BY_MARKETID_SUCCESS = 'USER_POSITION_BY_MARKETID_SUCCESS';
export const USER_POSITION_BY_MARKETID_FAILURE = 'USER_POSITION_BY_MARKETID_FAILURE';

//user/domainList

export const USER_DOMAIN_LIST_REQUEST = 'USER_DOMAIN_LIST_REQUEST';
export const USER_DOMAIN_LIST_SUCCESS = 'USER_DOMAIN_LIST_SUCCESS';
export const USER_DOMAIN_LIST_FAILURE = 'USER_DOMAIN_LIST_FAILURE';

export const USER_SEARCH_CLEAN = 'USER_SEARCH_CLEAN'


export const GET_MATKA_LIST_REQUEST = 'GET_MATKA_LIST_REQUEST';
export const GET_MATKA_LIST_SUCCESS = 'GET_MATKA_LIST_SUCCESS';
export const GET_MATKA_LIST_FAILURE = 'GET_MATKA_LIST_FAILURE';


export const MATKA_BET_LIST_REQUEST = 'MATKA_BET_LIST_REQUEST';
export const MATKA_BET_LIST_SUCCESS = 'MATKA_BET_LIST_SUCCESS';
export const MATKA_BET_LIST_FAILURE = 'MATKA_BET_LIST_FAILURE';

export const SPORTS_BET_LIST_CLEAN = 'SPORTS_BET_LIST_CLEAN';




export const MATKA_COIN_UPDATE_REQUEST = 'MATKA_COIN_UPDATE_REQUEST';
export const MATKA_COIN_UPDATE_SUCCESS = 'MATKA_COIN_UPDATE_SUCCESS';
export const MATKA_COIN_UPDATE_FAILURE = 'MATKA_COIN_UPDATE_FAILURE';

export const DAY_WISE_MATKA_REPORT_REQUEST = 'DAY_WISE_MATKA_REPORT_REQUEST';
export const DAY_WISE_MATKA_REPORT_SUCCESS = 'DAY_WISE_MATKA_REPORT_SUCCESS';
export const DAY_WISE_MATKA_REPORT_FAILURE = 'DAY_WISE_MATKA_REPORT_FAILURE';

export const COUNT_MATKA_BETS_REQUEST = 'COUNT_MATKA_BETS_REQUEST';
export const COUNT_MATKA_BETS_SUCCESS = 'COUNT_MATKA_BETS_SUCCESS';
export const COUNT_MATKA_BETS_FAILURE = 'COUNT_MATKA_BETS_FAILURE';


export const MATKA_PROFIT_LOSS_REQUEST = 'MATKA_PROFIT_LOSS_REQUEST';
export const MATKA_PROFIT_LOSS_SUCCESS = 'MATKA_PROFIT_LOSS_SUCCESS';
export const MATKA_PROFIT_LOSS_FAILURE = 'MATKA_PROFIT_LOSS_FAILURE';